// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://brisleonnlbzqkdqoubk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJyaXNsZW9ubmxienFrZHFvdWJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ1MTc0NjQsImV4cCI6MjA1MDA5MzQ2NH0.ok0xrYW-ZZFG2c8uVNsYLOgmzVoTshL7ic8bgDjm6g0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);